# Generated by Django 5.0 on 2023-12-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_app", "0003_employeedetail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeDetail",
        ),
    ]
