# Generated by Django 5.0 on 2023-12-21 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("workflow_app", "0004_delete_employeedetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDetail",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("emp_id", models.SmallIntegerField()),
                ("dept", models.CharField(max_length=30)),
                ("designation", models.CharField(max_length=100)),
                ("phone_no", models.CharField(max_length=13)),
            ],
        ),
    ]
