# Generated by Django 5.0 on 2023-12-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_app", "0005_employeedetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appraisalrequest",
            name="user",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="user",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="promotionrequest",
            name="user",
            field=models.CharField(max_length=30),
        ),
    ]
